<?php
/**
 * Initialize the options before anything else.
 */
add_action( 'admin_init', 'unitheme_options', 1 );

/**
 * Build the custom settings & update OptionTree.
 */
function unitheme_options() {
  /**
   * Get a copy of the saved settings array.
   */
  $saved_settings = get_option( 'option_tree_settings', array() );

  /**
   * Custom settings array that will eventually be
   * passes to the OptionTree Settings API Class.
   */
  $unitheme_settings = array(
    'contextual_help' => array(
      'content'       => array(
        array(
          'id'        => 'general_help',
          'title'     => esc_html__('General', 'bauhaus'),
          'content'   => esc_html__('<p><strong>Header layout</strong>. You may choose between two types of header. The first one is simple header with a white background and black colour of the texts. The second one has a transparent background.</p>', 'bauhaus')
        ),
        array(
          'id'        => 'logo_help',
          'title'     => esc_html__('Logo', 'bauhaus'),
          'content'   => esc_html__('<p><strong>Logo settings</strong>. You can upload three files. Each of them can be in different style. "Logo A" will be used if you choose Header Layout 1. It is also better if "Logo B" will be with white (light in general) colour outlines and "Logo C" will be with black (dark in general) colour outlines.</p>', 'bauhaus')
        )
      ),
      'sidebar'       => '',
    ),
    'sections'        => array(
      array(
        'id'          => 'general',
        'title'       => esc_html__('General', 'bauhaus')
      ),
      array(
        'id'          => 'logo',
        'title'       => esc_html__('Logo settings', 'bauhaus')
      ),
      array(
        'id'          => 'fonts',
        'title'       => esc_html__('Fonts', 'bauhaus')
      ),
      array(
        'id'          => 'home',
        'title'       => esc_html__('"Home" page settings', 'bauhaus')
      ),
      array(
        'id'          => 'contact',
        'title'       => esc_html__('"Contact" page settings', 'bauhaus')
      ),
      array(
        'id'          => 'social',
        'title'       => esc_html__('Socials', 'bauhaus')
      )
    ),
    'settings'        => array(
      array(
        'id'          => 'uni_header_layout',
        'label'       => esc_html__( 'Header layout', 'bauhaus' ),
        'desc'        => esc_html__( 'Choose a header layout', 'bauhaus' ),
        'std'         => 'header1',
        'type'        => 'radio',
        'section'     => 'general',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'min_max_step'=> '',
        'class'       => '',
        'condition'   => '',
        'operator'    => 'and',
        'choices'     => array(
          array(
            'value'       => 'header1',
            'label'       => esc_html__( 'Layout 1: header with a white background', 'bauhaus' ),
            'src'         => ''
          ),
          array(
            'value'       => 'header2',
            'label'       => esc_html__( 'Layout 2: header with a transparent background', 'bauhaus' ),
            'src'         => ''
          )
        )
      ),
      array(
        'id'          => 'uni_archive_layout',
        'label'       => esc_html__( 'Style of archive pages', 'bauhaus' ),
        'desc'        => esc_html__( 'Choose a style of archive pages (categories, tags)', 'bauhaus' ),
        'std'         => 'blog1',
        'type'        => 'radio',
        'section'     => 'general',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'min_max_step'=> '',
        'class'       => '',
        'condition'   => '',
        'operator'    => 'and',
        'choices'     => array(
          array(
            'value'       => 'blog1',
            'label'       => esc_html__( 'Layout 1: like the "Blog One" template', 'bauhaus' ),
            'src'         => ''
          ),
          array(
            'value'       => 'blog2',
            'label'       => esc_html__( 'Layout 2: like the "Blog Two" template', 'bauhaus' ),
            'src'         => ''
          )
        )
      ),
      array(
        'id'          => 'uni_display_similar_posts',
        'label'       => esc_html__( 'Enable/Disable displaying similar posts on single', 'bauhaus' ),
        'desc'        => esc_html__( 'This is a global option and it works for the whole website. Posts which are similar by tags can be displayed below post content.', 'bauhaus' ),
        'std'         => 'off',
        'type'        => 'on-off',
        'section'     => 'general',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'min_max_step'=> '',
        'class'       => '',
        'condition'   => '',
        'operator'    => 'and'
      ),
      array(
        'id'          => 'uni_portfolio_page',
        'label'       => esc_html__( 'Portfolio page', 'bauhaus' ),
        'desc'        => esc_html__( 'Select your Portfolio page. A link to this page will be added to the special icon on the slider on single project page. This is a global option and it can be overriden on per project basis.', 'bauhaus' ),
        'std'         => '',
        'type'        => 'custom-post-type-select',
        'section'     => 'general',
        'rows'        => '',
        'post_type'   => 'page',
        'taxonomy'    => '',
        'min_max_step'=> '',
        'class'       => '',
        'condition'   => '',
        'operator'    => 'and'
      ),
      array(
        'id'          => 'uni_brands_grayscale_enable',
        'label'       => esc_html__( 'Enable/Disable displaying all brands (logotypes) in black and white', 'bauhaus' ),
        'desc'        => esc_html__( 'This is a global option and it works for both block on home page and block on "About" page', 'bauhaus' ),
        'std'         => 'off',
        'type'        => 'on-off',
        'section'     => 'general',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'min_max_step'=> '',
        'class'       => '',
        'condition'   => '',
        'operator'    => 'and'
      ),
      array(
        'id'          => 'uni_filter_type',
        'label'       => esc_html__( 'Enable filter by types of projects', 'bauhaus' ),
        'desc'        => '',
        'std'         => 'on',
        'type'        => 'on-off',
        'section'     => 'general',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'min_max_step'=> '',
        'class'       => '',
        'condition'   => '',
        'operator'    => 'and'
      ),
      array(
        'id'          => 'uni_filter_loc',
        'label'       => esc_html__( 'Enable filter by locations of projects', 'bauhaus' ),
        'desc'        => '',
        'std'         => 'off',
        'type'        => 'on-off',
        'section'     => 'general',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'min_max_step'=> '',
        'class'       => '',
        'condition'   => '',
        'operator'    => 'and'
      ),
      array(
        'id'          => 'uni_filter_status',
        'label'       => esc_html__( 'Enable filter by statuses of projects', 'bauhaus' ),
        'desc'        => '',
        'std'         => 'off',
        'type'        => 'on-off',
        'section'     => 'general',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'min_max_step'=> '',
        'class'       => '',
        'condition'   => '',
        'operator'    => 'and'
      ),
      array(
        'id'          => 'uni_filter_year',
        'label'       => esc_html__( 'Enable filter by years of projects', 'bauhaus' ),
        'desc'        => '',
        'std'         => 'off',
        'type'        => 'on-off',
        'section'     => 'general',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'min_max_step'=> '',
        'class'       => '',
        'condition'   => '',
        'operator'    => 'and'
      ),
      array(
        'id'          => 'uni_footer_text',
        'label'       => esc_html__( 'Text in the footer', 'bauhaus' ),
        'desc'        => esc_html__( 'Add your own text to the footer', 'bauhaus' ),
        'std'         => '',
        'type'        => 'textarea-simple',
        'section'     => 'general',
        'rows'        => '5',
        'post_type'   => '',
        'taxonomy'    => '',
        'min_max_step'=> '',
        'class'       => '',
        'condition'   => '',
        'operator'    => 'and'
      ),
      array(
        'id'          => 'uni_logo_a',
        'label'       => esc_html__( 'Logo A', 'bauhaus' ),
        'desc'        => esc_html__( 'Logo A will be used with Headear layout 1', 'bauhaus' ),
        'std'         => '',
        'type'        => 'upload',
        'section'     => 'logo',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'min_max_step'=> '',
        'class'       => 'ot-upload-attachment-id',
        'condition'   => '',
        'operator'    => 'and'
      ),
      array(
        'id'          => 'uni_logo_b',
        'label'       => esc_html__( 'Logo B', 'bauhaus' ),
        'desc'        => esc_html__( 'Logo B should be a white version of the logo and will be used with Headear layout 2', 'bauhaus' ),
        'std'         => '',
        'type'        => 'upload',
        'section'     => 'logo',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'min_max_step'=> '',
        'class'       => 'ot-upload-attachment-id',
        'condition'   => '',
        'operator'    => 'and'
      ),
      array(
        'id'          => 'uni_logo_c',
        'label'       => esc_html__( 'Logo C', 'bauhaus' ),
        'desc'        => esc_html__( 'Logo C should be a black version of the logo and will be used with Headear layout 2', 'bauhaus' ),
        'std'         => '',
        'type'        => 'upload',
        'section'     => 'logo',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'min_max_step'=> '',
        'class'       => 'ot-upload-attachment-id',
        'condition'   => '',
        'operator'    => 'and'
      ),
      array(
        'id'          => 'uni_google_fonts',
        'label'       => esc_html__( 'Custom Google Fonts', 'bauhaus' ),
        'desc'        => esc_html__( 'You can define custom Google fonts here. Please, use the first for regular text and the second for headings. Default are: Montserrat (700, regular) and Open Sans (700, 300, regular)', 'bauhaus' ),
        'std'         => array(
          array(
            'family'    => 'montserrat',
            'variants'  => array( '700', 'regular' ),
            'subsets'   => array( 'latin' )
          ),
          array(
            'family'    => 'opensans',
            'variants'  => array( '700', '300', 'regular' ),
            'subsets'   => array( 'latin' )
          )
        ),
        'type'        => 'google-fonts',
        'section'     => 'fonts',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'min_max_step'=> '',
        'class'       => '',
        'condition'   => '',
        'operator'    => 'and'
      ),
      array(
        'id'          => 'uni_home_slider_textblock',
        'label'       => '',
        'desc'        => esc_html__( 'Simple built-in slider', 'bauhaus' ),
        'std'         => '',
        'type'        => 'textblock',
        'section'     => 'home',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'min_max_step'=> '',
        'class'       => '',
        'condition'   => '',
        'operator'    => 'and'
      ),
      array(
        'id'          => 'uni_home_slider_enable',
        'label'       => esc_html__( 'Enable/Disable simple slider', 'bauhaus' ),
        'desc'        => '',
        'std'         => 'off',
        'type'        => 'on-off',
        'section'     => 'home',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'min_max_step'=> '',
        'class'       => '',
        'condition'   => '',
        'operator'    => 'and'
      ),
      array(
        'id'          => 'uni_home_about_one_textblock',
        'label'       => '',
        'desc'        => esc_html__( 'Nice promo block "About Us" #1', 'bauhaus' ),
        'std'         => '',
        'type'        => 'textblock',
        'section'     => 'home',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'min_max_step'=> '',
        'class'       => '',
        'condition'   => '',
        'operator'    => 'and'
      ),
      array(
        'id'          => 'uni_home_about_one_enable',
        'label'       => esc_html__( 'Enable/Disable "About Us" block #1', 'bauhaus' ),
        'desc'        => '',
        'std'         => 'off',
        'type'        => 'on-off',
        'section'     => 'home',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'min_max_step'=> '',
        'class'       => '',
        'condition'   => '',
        'operator'    => 'and'
      ),
      array(
        'id'          => 'uni_home_about_one_colour',
        'label'       => esc_html__( 'Colour of texts for "About Us" block #1', 'bauhaus' ),
        'desc'        => esc_html__( 'Choose one of the colours - white or black - as a colour for texts which are over the block. If your block is mainly dark then choose "White colour" to make white all the texts. And vise versa. The default colour is "white".', 'bauhaus' ),
        'std'         => 'white',
        'type'        => 'radio',
        'section'     => 'home',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'min_max_step'=> '',
        'class'       => '',
        'condition'   => 'uni_home_about_one_enable:is(on)',
        'operator'    => 'and',
        'choices'     => array(
          array(
            'value'       => 'white',
            'label'       => esc_html__( 'White colour', 'bauhaus' ),
            'src'         => ''
          ),
          array(
            'value'       => 'black',
            'label'       => esc_html__( 'Black colour', 'bauhaus' ),
            'src'         => ''
          )
        )
      ),
      array(
        'id'          => 'uni_home_about_one_bg',
        'label'       => esc_html__( 'Custom image in background for "About Us" block #1', 'bauhaus' ),
        'desc'        => esc_html__( 'Add custom image in background "About Us" block #1', 'bauhaus' ),
        'std'         => '',
        'type'        => 'upload',
        'section'     => 'home',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'min_max_step'=> '',
        'class'       => 'ot-upload-attachment-id',
        'condition'   => 'uni_home_about_one_enable:is(on)',
        'operator'    => 'and'
      ),
      array(
        'id'          => 'uni_home_about_one_subtitle',
        'label'       => esc_html__( 'Subtitle for "About Us" block #1', 'bauhaus' ),
        'desc'        => esc_html__( 'Add subtitle for "About Us" block #1', 'bauhaus' ),
        'std'         => '',
        'type'        => 'text',
        'section'     => 'home',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'min_max_step'=> '',
        'class'       => '',
        'condition'   => 'uni_home_about_one_enable:is(on)',
        'operator'    => 'and'
      ),
      array(
        'id'          => 'uni_home_about_one_title',
        'label'       => esc_html__( 'Title for "About Us" block #1', 'bauhaus' ),
        'desc'        => esc_html__( 'Add title for "About Us" block #1', 'bauhaus' ),
        'std'         => '',
        'type'        => 'text',
        'section'     => 'home',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'min_max_step'=> '',
        'class'       => '',
        'condition'   => 'uni_home_about_one_enable:is(on)',
        'operator'    => 'and'
      ),
      array(
        'id'          => 'uni_home_about_one_button_uri',
        'label'       => esc_html__( 'An URI for "see more" button for "About Us" block #1', 'bauhaus' ),
        'desc'        => esc_html__( 'Add URI or leave blank and this button won\'t be shown at all!', 'bauhaus' ),
        'std'         => '',
        'type'        => 'text',
        'section'     => 'home',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'min_max_step'=> '',
        'class'       => '',
        'condition'   => 'uni_home_about_one_enable:is(on)',
        'operator'    => 'and'
      ),
      array(
        'id'          => 'uni_home_about_one_button_text',
        'label'       => esc_html__( 'Text for "see more" button for "About Us" block #1', 'bauhaus' ),
        'desc'        => esc_html__( 'Add custom text for the button', 'bauhaus' ),
        'std'         => '',
        'type'        => 'text',
        'section'     => 'home',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'min_max_step'=> '',
        'class'       => '',
        'condition'   => 'uni_home_about_one_enable:is(on)',
        'operator'    => 'and'
      ),
      array(
        'id'          => 'uni_home_about_two_textblock',
        'label'       => '',
        'desc'        => esc_html__( 'Nice promo block "About Us" #2', 'bauhaus' ),
        'std'         => '',
        'type'        => 'textblock',
        'section'     => 'home',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'min_max_step'=> '',
        'class'       => '',
        'condition'   => '',
        'operator'    => 'and'
      ),
      array(
        'id'          => 'uni_home_about_two_enable',
        'label'       => esc_html__( 'Enable/Disable "About Us" block #2', 'bauhaus' ),
        'desc'        => '',
        'std'         => 'off',
        'type'        => 'on-off',
        'section'     => 'home',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'min_max_step'=> '',
        'class'       => '',
        'condition'   => '',
        'operator'    => 'and'
      ),
      array(
        'id'          => 'uni_home_about_two_bg',
        'label'       => esc_html__( 'Custom image in background for "About Us" block #2', 'bauhaus' ),
        'desc'        => esc_html__( 'Add custom image in background "About Us" block #2', 'bauhaus' ),
        'std'         => '',
        'type'        => 'upload',
        'section'     => 'home',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'min_max_step'=> '',
        'class'       => 'ot-upload-attachment-id',
        'condition'   => 'uni_home_about_two_enable:is(on)',
        'operator'    => 'and'
      ),
      array(
        'id'          => 'uni_home_about_two_title',
        'label'       => esc_html__( 'Title for "About Us" block #2', 'bauhaus' ),
        'desc'        => esc_html__( 'Add title for "About Us" block #2', 'bauhaus' ),
        'std'         => '',
        'type'        => 'text',
        'section'     => 'home',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'min_max_step'=> '',
        'class'       => '',
        'condition'   => 'uni_home_about_two_enable:is(on)',
        'operator'    => 'and'
      ),
      array(
        'id'          => 'uni_home_about_two_text',
        'label'       => esc_html__( 'Custom text for "About Us" block #2', 'bauhaus' ),
        'desc'        => '',
        'std'         => '',
        'type'        => 'textarea-simple',
        'section'     => 'home',
        'rows'        => '10',
        'post_type'   => '',
        'taxonomy'    => '',
        'min_max_step'=> '',
        'class'       => '',
        'condition'   => 'uni_home_about_two_enable:is(on)',
        'operator'    => 'and'
      ),
      array(
        'id'          => 'uni_home_about_two_button_uri',
        'label'       => esc_html__( 'An URI for "learn more" button and for the whole "About Us" block #2', 'bauhaus' ),
        'desc'        => '',
        'std'         => '',
        'type'        => 'text',
        'section'     => 'home',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'min_max_step'=> '',
        'class'       => '',
        'condition'   => 'uni_home_about_two_enable:is(on)',
        'operator'    => 'and'
      ),
      array(
        'id'          => 'uni_home_about_two_button_text',
        'label'       => esc_html__( 'Text for "learn more" button for "About Us" block #2', 'bauhaus' ),
        'desc'        => esc_html__( 'Add custom text for the button', 'bauhaus' ),
        'std'         => '',
        'type'        => 'text',
        'section'     => 'home',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'min_max_step'=> '',
        'class'       => '',
        'condition'   => 'uni_home_about_two_enable:is(on)',
        'operator'    => 'and'
      ),
      array(
        'id'          => 'uni_home_grid_custom_textblock',
        'label'       => '',
        'desc'        => esc_html__( 'A unique grid with custom content on home page. Total are 6 items, but you may also display first three items or second three items separately.  Important: in order to show the first three items you have to add URIs for the first three items. The same is for the second three items. It means that you can not just display first and fourth items, for instance. Only by three items at once and only first three or second three or all six items. Also, the second and the sixth items haven\'t fields for text.', 'bauhaus' ),
        'std'         => '',
        'type'        => 'textblock',
        'section'     => 'home',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'min_max_step'=> '',
        'class'       => '',
        'condition'   => '',
        'operator'    => 'and'
      ),
      array(
        'id'          => 'uni_home_grid_custom_enable',
        'label'       => esc_html__( 'Enable/Disable grid with custom content', 'bauhaus' ),
        'desc'        => '',
        'std'         => 'off',
        'type'        => 'on-off',
        'section'     => 'home',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'min_max_step'=> '',
        'class'       => '',
        'condition'   => '',
        'operator'    => 'and'
      ),
      array(
        'id'          => 'uni_home_grid_custom_title_one',
        'label'       => esc_html__( 'Title for the first item in grid', 'bauhaus' ),
        'desc'        => esc_html__( 'Add custom title for the first item in grid', 'bauhaus' ),
        'std'         => '',
        'type'        => 'text',
        'section'     => 'home',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'min_max_step'=> '',
        'class'       => '',
        'condition'   => 'uni_home_grid_custom_enable:is(on)',
        'operator'    => 'and'
      ),
      array(
        'id'          => 'uni_home_grid_custom_text_one',
        'label'       => esc_html__( 'Custom text for the first item in grid', 'bauhaus' ),
        'desc'        => esc_html__( 'Add custom text for the first item in grid', 'bauhaus' ),
        'std'         => '',
        'type'        => 'textarea-simple',
        'section'     => 'home',
        'rows'        => '5',
        'post_type'   => '',
        'taxonomy'    => '',
        'min_max_step'=> '',
        'class'       => '',
        'condition'   => 'uni_home_grid_custom_enable:is(on)',
        'operator'    => 'and'
      ),
      array(
        'id'          => 'uni_home_grid_custom_image_one',
        'label'       => esc_html__( 'Image for the first item in grid', 'bauhaus' ),
        'desc'        => esc_html__( 'Upload an image for the first item in grid. Thumbnail 684x684 will be shown here.', 'bauhaus' ),
        'std'         => '',
        'type'        => 'upload',
        'section'     => 'home',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'min_max_step'=> '',
        'class'       => 'ot-upload-attachment-id',
        'condition'   => 'uni_home_grid_custom_enable:is(on)',
        'operator'    => 'and'
      ),
      array(
        'id'          => 'uni_home_grid_custom_uri_one',
        'label'       => esc_html__( 'URI for the first item in grid', 'bauhaus' ),
        'desc'        => esc_html__( 'Add custom URI for the first item in grid', 'bauhaus' ),
        'std'         => '',
        'type'        => 'text',
        'section'     => 'home',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'min_max_step'=> '',
        'class'       => '',
        'condition'   => 'uni_home_grid_custom_enable:is(on)',
        'operator'    => 'and'
      ),
      array(
        'id'          => 'uni_home_grid_custom_title_two',
        'label'       => esc_html__( 'Title for the second item in grid', 'bauhaus' ),
        'desc'        => esc_html__( 'Add custom title for the second item in grid', 'bauhaus' ),
        'std'         => '',
        'type'        => 'text',
        'section'     => 'home',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'min_max_step'=> '',
        'class'       => '',
        'condition'   => 'uni_home_grid_custom_enable:is(on)',
        'operator'    => 'and'
      ),
      array(
        'id'          => 'uni_home_grid_custom_image_two',
        'label'       => esc_html__( 'Image for the second item in grid', 'bauhaus' ),
        'desc'        => esc_html__( 'Upload an image for the second item in grid. Thumbnail 342x342 will be shown here.', 'bauhaus' ),
        'std'         => '',
        'type'        => 'upload',
        'section'     => 'home',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'min_max_step'=> '',
        'class'       => 'ot-upload-attachment-id',
        'condition'   => 'uni_home_grid_custom_enable:is(on)',
        'operator'    => 'and'
      ),
      array(
        'id'          => 'uni_home_grid_custom_uri_two',
        'label'       => esc_html__( 'URI for the second item in grid', 'bauhaus' ),
        'desc'        => esc_html__( 'Add custom URI for the second item in grid', 'bauhaus' ),
        'std'         => '',
        'type'        => 'text',
        'section'     => 'home',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'min_max_step'=> '',
        'class'       => '',
        'condition'   => 'uni_home_grid_custom_enable:is(on)',
        'operator'    => 'and'
      ),
      array(
        'id'          => 'uni_home_grid_custom_title_three',
        'label'       => esc_html__( 'Title for the third item in grid', 'bauhaus' ),
        'desc'        => esc_html__( 'Add custom title for the third item in grid', 'bauhaus' ),
        'std'         => '',
        'type'        => 'text',
        'section'     => 'home',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'min_max_step'=> '',
        'class'       => '',
        'condition'   => 'uni_home_grid_custom_enable:is(on)',
        'operator'    => 'and'
      ),
      array(
        'id'          => 'uni_home_grid_custom_text_three',
        'label'       => esc_html__( 'Custom text for the third item in grid', 'bauhaus' ),
        'desc'        => esc_html__( 'Add custom text for the third item in grid', 'bauhaus' ),
        'std'         => '',
        'type'        => 'textarea-simple',
        'section'     => 'home',
        'rows'        => '5',
        'post_type'   => '',
        'taxonomy'    => '',
        'min_max_step'=> '',
        'class'       => '',
        'condition'   => 'uni_home_grid_custom_enable:is(on)',
        'operator'    => 'and'
      ),
      array(
        'id'          => 'uni_home_grid_custom_image_three',
        'label'       => esc_html__( 'Image for the third item in grid', 'bauhaus' ),
        'desc'        => esc_html__( 'Upload an image for the third item in grid. Thumbnail 342x342 will be shown here.', 'bauhaus' ),
        'std'         => '',
        'type'        => 'upload',
        'section'     => 'home',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'min_max_step'=> '',
        'class'       => 'ot-upload-attachment-id',
        'condition'   => 'uni_home_grid_custom_enable:is(on)',
        'operator'    => 'and'
      ),
      array(
        'id'          => 'uni_home_grid_custom_uri_three',
        'label'       => esc_html__( 'URI for the third item in grid', 'bauhaus' ),
        'desc'        => esc_html__( 'Add custom URI for the third item in grid', 'bauhaus' ),
        'std'         => '',
        'type'        => 'text',
        'section'     => 'home',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'min_max_step'=> '',
        'class'       => '',
        'condition'   => 'uni_home_grid_custom_enable:is(on)',
        'operator'    => 'and'
      ),
      array(
        'id'          => 'uni_home_grid_custom_title_four',
        'label'       => esc_html__( 'Title for the fourth item in grid', 'bauhaus' ),
        'desc'        => esc_html__( 'Add custom title for the fourth item in grid', 'bauhaus' ),
        'std'         => '',
        'type'        => 'text',
        'section'     => 'home',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'min_max_step'=> '',
        'class'       => '',
        'condition'   => 'uni_home_grid_custom_enable:is(on)',
        'operator'    => 'and'
      ),
      array(
        'id'          => 'uni_home_grid_custom_text_four',
        'label'       => esc_html__( 'Custom text for the fourth item in grid', 'bauhaus' ),
        'desc'        => esc_html__( 'Add custom text for the fourth item in grid', 'bauhaus' ),
        'std'         => '',
        'type'        => 'textarea-simple',
        'section'     => 'home',
        'rows'        => '5',
        'post_type'   => '',
        'taxonomy'    => '',
        'min_max_step'=> '',
        'class'       => '',
        'condition'   => 'uni_home_grid_custom_enable:is(on)',
        'operator'    => 'and'
      ),
      array(
        'id'          => 'uni_home_grid_custom_image_four',
        'label'       => esc_html__( 'Image for the fourth item in grid', 'bauhaus' ),
        'desc'        => esc_html__( 'Upload an image for the fourth item in grid. Thumbnail 342x342 will be shown here.', 'bauhaus' ),
        'std'         => '',
        'type'        => 'upload',
        'section'     => 'home',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'min_max_step'=> '',
        'class'       => 'ot-upload-attachment-id',
        'condition'   => 'uni_home_grid_custom_enable:is(on)',
        'operator'    => 'and'
      ),
      array(
        'id'          => 'uni_home_grid_custom_uri_four',
        'label'       => esc_html__( 'URI for the fourth item in grid', 'bauhaus' ),
        'desc'        => esc_html__( 'Add custom URI for the fourth item in grid', 'bauhaus' ),
        'std'         => '',
        'type'        => 'text',
        'section'     => 'home',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'min_max_step'=> '',
        'class'       => '',
        'condition'   => 'uni_home_grid_custom_enable:is(on)',
        'operator'    => 'and'
      ),
      array(
        'id'          => 'uni_home_grid_custom_title_five',
        'label'       => esc_html__( 'Title for the fifth item in grid', 'bauhaus' ),
        'desc'        => esc_html__( 'Add custom title for the fifth item in grid', 'bauhaus' ),
        'std'         => '',
        'type'        => 'text',
        'section'     => 'home',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'min_max_step'=> '',
        'class'       => '',
        'condition'   => 'uni_home_grid_custom_enable:is(on)',
        'operator'    => 'and'
      ),
      array(
        'id'          => 'uni_home_grid_custom_text_five',
        'label'       => esc_html__( 'Custom text for the fifth item in grid', 'bauhaus' ),
        'desc'        => esc_html__( 'Add custom text for the fifth item in grid', 'bauhaus' ),
        'std'         => '',
        'type'        => 'textarea-simple',
        'section'     => 'home',
        'rows'        => '5',
        'post_type'   => '',
        'taxonomy'    => '',
        'min_max_step'=> '',
        'class'       => '',
        'condition'   => 'uni_home_grid_custom_enable:is(on)',
        'operator'    => 'and'
      ),
      array(
        'id'          => 'uni_home_grid_custom_image_five',
        'label'       => esc_html__( 'Image for the fifth item in grid', 'bauhaus' ),
        'desc'        => esc_html__( 'Upload an image for the fifth item in grid. Thumbnail 342x342 will be shown here.', 'bauhaus' ),
        'std'         => '',
        'type'        => 'upload',
        'section'     => 'home',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'min_max_step'=> '',
        'class'       => 'ot-upload-attachment-id',
        'condition'   => 'uni_home_grid_custom_enable:is(on)',
        'operator'    => 'and'
      ),
      array(
        'id'          => 'uni_home_grid_custom_uri_five',
        'label'       => esc_html__( 'URI for the fifth item in grid', 'bauhaus' ),
        'desc'        => esc_html__( 'Add custom URI for the fifth item in grid', 'bauhaus' ),
        'std'         => '',
        'type'        => 'text',
        'section'     => 'home',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'min_max_step'=> '',
        'class'       => '',
        'condition'   => 'uni_home_grid_custom_enable:is(on)',
        'operator'    => 'and'
      ),
      array(
        'id'          => 'uni_home_grid_custom_title_six',
        'label'       => esc_html__( 'Title for the sixth item in grid', 'bauhaus' ),
        'desc'        => esc_html__( 'Add custom title for the sixth item in grid', 'bauhaus' ),
        'std'         => '',
        'type'        => 'text',
        'section'     => 'home',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'min_max_step'=> '',
        'class'       => '',
        'condition'   => 'uni_home_grid_custom_enable:is(on)',
        'operator'    => 'and'
      ),
      array(
        'id'          => 'uni_home_grid_custom_image_six',
        'label'       => esc_html__( 'Image for the sixth item in grid', 'bauhaus' ),
        'desc'        => esc_html__( 'Upload an image for the sixth item in grid. Thumbnail 684x684 will be shown here.', 'bauhaus' ),
        'std'         => '',
        'type'        => 'upload',
        'section'     => 'home',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'min_max_step'=> '',
        'class'       => 'ot-upload-attachment-id',
        'condition'   => 'uni_home_grid_custom_enable:is(on)',
        'operator'    => 'and'
      ),
      array(
        'id'          => 'uni_home_grid_custom_uri_six',
        'label'       => esc_html__( 'URI for the sixth item in grid', 'bauhaus' ),
        'desc'        => esc_html__( 'Add custom URI for the sixth item in grid', 'bauhaus' ),
        'std'         => '',
        'type'        => 'text',
        'section'     => 'home',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'min_max_step'=> '',
        'class'       => '',
        'condition'   => 'uni_home_grid_custom_enable:is(on)',
        'operator'    => 'and'
      ),
      array(
        'id'          => 'uni_home_services_enable',
        'label'       => esc_html__( 'Enable/Disable "Our Services" block', 'bauhaus' ),
        'desc'        => '',
        'std'         => 'off',
        'type'        => 'on-off',
        'section'     => 'home',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'min_max_step'=> '',
        'class'       => '',
        'condition'   => '',
        'operator'    => 'and'
      ),
      array(
        'id'          => 'uni_home_services_title',
        'label'       => esc_html__( 'Custom title for "Our Services" block', 'bauhaus' ),
        'desc'        => esc_html__( 'Add custom title for "Our Services" block', 'bauhaus' ),
        'std'         => '',
        'type'        => 'text',
        'section'     => 'home',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'min_max_step'=> '',
        'class'       => '',
        'condition'   => 'uni_home_services_enable:is(on)',
        'operator'    => 'and'
      ),
      array(
        'id'          => 'uni_home_testimonials_enable',
        'label'       => esc_html__( 'Enable/Disable block with testimonials', 'bauhaus' ),
        'desc'        => '',
        'std'         => 'off',
        'type'        => 'on-off',
        'section'     => 'home',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'min_max_step'=> '',
        'class'       => '',
        'condition'   => '',
        'operator'    => 'and'
      ),
      array(
        'id'          => 'uni_home_testimonials_title',
        'label'       => esc_html__( 'Custom title for block with testimonials', 'bauhaus' ),
        'desc'        => esc_html__( 'Add custom title for block with testimonials', 'bauhaus' ),
        'std'         => '',
        'type'        => 'text',
        'section'     => 'home',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'min_max_step'=> '',
        'class'       => '',
        'condition'   => 'uni_home_testimonials_enable:is(on)',
        'operator'    => 'and'
      ),
      array(
        'id'          => 'uni_home_testimonials_bg',
        'label'       => esc_html__( 'Custom image in background for block with testimonials', 'bauhaus' ),
        'desc'        => esc_html__( 'Add custom image in background for block with testimonials', 'bauhaus' ),
        'std'         => '',
        'type'        => 'upload',
        'section'     => 'home',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'min_max_step'=> '',
        'class'       => 'ot-upload-attachment-id',
        'condition'   => 'uni_home_testimonials_enable:is(on)',
        'operator'    => 'and'
      ),
      array(
        'id'          => 'uni_home_brands_enable',
        'label'       => esc_html__( 'Enable/Disable block with brands', 'bauhaus' ),
        'desc'        => '',
        'std'         => 'off',
        'type'        => 'on-off',
        'section'     => 'home',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'min_max_step'=> '',
        'class'       => '',
        'condition'   => '',
        'operator'    => 'and'
      ),
      array(
        'id'          => 'uni_home_brands_title',
        'label'       => esc_html__( 'Custom title for block brands (logos)', 'bauhaus' ),
        'desc'        => esc_html__( 'Add custom title for block brands (logos)', 'bauhaus' ),
        'std'         => '',
        'type'        => 'text',
        'section'     => 'home',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'min_max_step'=> '',
        'class'       => '',
        'condition'   => 'uni_home_brands_enable:is(on)',
        'operator'    => 'and'
      ),
      array(
        'id'          => 'uni_home_contact_enable',
        'label'       => esc_html__( 'Enable/Disable block with a map and contact information', 'bauhaus' ),
        'desc'        => '',
        'std'         => 'off',
        'type'        => 'on-off',
        'section'     => 'home',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'min_max_step'=> '',
        'class'       => '',
        'condition'   => '',
        'operator'    => 'and'
      ),
      array(
        'id'          => 'uni_home_contact_send_link_enable',
        'label'       => esc_html__( 'Show/Hide "send email" link', 'bauhaus' ),
        'desc'        => '',
        'std'         => 'off',
        'type'        => 'on-off',
        'section'     => 'home',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'min_max_step'=> '',
        'class'       => '',
        'condition'   => 'uni_home_contact_enable:is(on)',
        'operator'    => 'and'
      ),
      array(
        'id'          => 'uni_home_contact_send_link_text',
        'label'       => esc_html__( 'Custom text for "send email" button', 'bauhaus' ),
        'desc'        => esc_html__( 'Default is "Send Email"', 'bauhaus' ),
        'std'         => '',
        'type'        => 'text',
        'section'     => 'home',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'min_max_step'=> '',
        'class'       => '',
        'condition'   => 'uni_home_contact_enable:is(on),uni_home_contact_send_link_enable:is(on)',
        'operator'    => 'and'
      ),
      array(
        'id'          => 'uni_home_contact_send_link_uri',
        'label'       => esc_html__( 'Custom URI for "send email" button', 'bauhaus' ),
        'desc'        => '',
        'std'         => '',
        'type'        => 'text',
        'section'     => 'home',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'min_max_step'=> '',
        'class'       => '',
        'condition'   => 'uni_home_contact_enable:is(on),uni_home_contact_send_link_enable:is(on)',
        'operator'    => 'and'
      ),
      array(
        'id'          => 'uni_coordinates',
        'label'       => esc_html__( 'Google map coordinates', 'bauhaus' ),
        'desc'        => esc_html__( 'For example: "41.404182,2.199451"', 'bauhaus' ),
        'std'         => '',
        'type'        => 'text',
        'section'     => 'contact',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'min_max_step'=> '',
        'class'       => '',
        'condition'   => '',
        'operator'    => 'and'
      ),
      array(
        'id'          => 'uni_zoom',
        'label'       => esc_html__( 'Google map zoom', 'bauhaus' ),
        'desc'        => '',
        'std'         => '14',
        'type'        => 'select',
        'section'     => 'contact',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'min_max_step'=> '',
        'class'       => '',
        'condition'   => '',
        'operator'    => 'and',
        'choices'     => array(
          array(
            'value'       => '6',
            'label'       => '6',
            'src'         => ''
          ),
          array(
            'value'       => '7',
            'label'       => '7',
            'src'         => ''
          ),
          array(
            'value'       => '8',
            'label'       => '8',
            'src'         => ''
          ),
          array(
            'value'       => '9',
            'label'       => '9',
            'src'         => ''
          ),
          array(
            'value'       => '10',
            'label'       => '10',
            'src'         => ''
          ),
          array(
            'value'       => '11',
            'label'       => '11',
            'src'         => ''
          ),
          array(
            'value'       => '12',
            'label'       => '12',
            'src'         => ''
          ),
          array(
            'value'       => '13',
            'label'       => '13',
            'src'         => ''
          ),
          array(
            'value'       => '14',
            'label'       => '14',
            'src'         => ''
          ),
          array(
            'value'       => '15',
            'label'       => '15',
            'src'         => ''
          ),
          array(
            'value'       => '16',
            'label'       => '16',
            'src'         => ''
          ),
          array(
            'value'       => '17',
            'label'       => '17',
            'src'         => ''
          ),
        )
      ),
      array(
        'id'          => 'uni_address',
        'label'       => esc_html__( 'Address to be displayed on the "Contact Us" page', 'bauhaus' ),
        'desc'        => '',
        'std'         => '',
        'type'        => 'text',
        'section'     => 'contact',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'min_max_step'=> '',
        'class'       => '',
        'condition'   => '',
        'operator'    => 'and'
      ),
      array(
        'id'          => 'uni_phone',
        'label'       => esc_html__( 'Phone number to be displayed on the "Contact Us" page', 'bauhaus' ),
        'desc'        => '',
        'std'         => '',
        'type'        => 'text',
        'section'     => 'contact',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'min_max_step'=> '',
        'class'       => '',
        'condition'   => '',
        'operator'    => 'and'
      ),
      array(
        'id'          => 'uni_email',
        'label'       => esc_html__( 'Email to be displayed on the "Contact Us" page', 'bauhaus' ),
        'desc'        => esc_html__( 'Also an information submitted via contact form will be sent to this email address', 'bauhaus' ),
        'std'         => '',
        'type'        => 'text',
        'section'     => 'contact',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'min_max_step'=> '',
        'class'       => '',
        'condition'   => '',
        'operator'    => 'and'
      ),
      array(
        'id'          => 'uni_contact_form_seven_id',
        'label'       => esc_html__( 'OR you can utilise Contact Form 7 form...', 'bauhaus' ),
        'desc'        => esc_html__( '... Just activate your Contact Form 7 plugin and define here the ID of the form', 'bauhaus' ),
        'std'         => '',
        'type'        => 'text',
        'section'     => 'contact',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'min_max_step'=> '',
        'class'       => '',
        'condition'   => '',
        'operator'    => 'and'
      ),
      array(
        'id'          => 'uni_email_link',
        'label'       => esc_html__( 'Add an Email link', 'bauhaus' ),
        'desc'        => '',
        'std'         => '',
        'type'        => 'text',
        'section'     => 'social',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'min_max_step'=> '',
        'class'       => '',
        'condition'   => '',
        'operator'    => 'and'
      ),
      array(
        'id'          => 'uni_fb_link',
        'label'       => esc_html__( 'Add a link to Facebook profile', 'bauhaus' ),
        'desc'        => '',
        'std'         => '',
        'type'        => 'text',
        'section'     => 'social',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'min_max_step'=> '',
        'class'       => '',
        'condition'   => '',
        'operator'    => 'and'
      ),
      array(
        'id'          => 'uni_youtube_link',
        'label'       => esc_html__( 'Add a link to YouTube profile', 'bauhaus' ),
        'desc'        => '',
        'std'         => '',
        'type'        => 'text',
        'section'     => 'social',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'min_max_step'=> '',
        'class'       => '',
        'condition'   => '',
        'operator'    => 'and'
      ),
      array(
        'id'          => 'uni_vimeo_link',
        'label'       => esc_html__( 'Add a link to Vimeo profile', 'bauhaus' ),
        'desc'        => '',
        'std'         => '',
        'type'        => 'text',
        'section'     => 'social',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'min_max_step'=> '',
        'class'       => '',
        'condition'   => '',
        'operator'    => 'and'
      ),
      array(
        'id'          => 'uni_tw_link',
        'label'       => esc_html__( 'Add a link to Twitter account', 'bauhaus' ),
        'desc'        => '',
        'std'         => '',
        'type'        => 'text',
        'section'     => 'social',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'min_max_step'=> '',
        'class'       => '',
        'condition'   => '',
        'operator'    => 'and'
      ),
      array(
        'id'          => 'uni_gp_link',
        'label'       => esc_html__( 'Add a link to Google Plus profile', 'bauhaus' ),
        'desc'        => '',
        'std'         => '',
        'type'        => 'text',
        'section'     => 'social',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'min_max_step'=> '',
        'class'       => '',
        'condition'   => '',
        'operator'    => 'and'
      ),
      array(
        'id'          => 'uni_in_link',
        'label'       => esc_html__( 'Add a link to Instagram profile', 'bauhaus' ),
        'desc'        => '',
        'std'         => '',
        'type'        => 'text',
        'section'     => 'social',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'min_max_step'=> '',
        'class'       => '',
        'condition'   => '',
        'operator'    => 'and'
      ),
      array(
        'id'          => 'uni_li_link',
        'label'       => esc_html__( 'Add a link to LinkedIn profile', 'bauhaus' ),
        'desc'        => '',
        'std'         => '',
        'type'        => 'text',
        'section'     => 'social',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'min_max_step'=> '',
        'class'       => '',
        'condition'   => '',
        'operator'    => 'and'
      ),
      array(
        'id'          => 'uni_pi_link',
        'label'       => esc_html__( 'Add a link to Pinterest profile', 'bauhaus' ),
        'desc'        => '',
        'std'         => '',
        'type'        => 'text',
        'section'     => 'social',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'min_max_step'=> '',
        'class'       => '',
        'condition'   => '',
        'operator'    => 'and'
      ),
      array(
        'id'          => 'uni_bl_link',
        'label'       => esc_html__( 'Add a link to Bloglovin account', 'bauhaus' ),
        'desc'        => '',
        'std'         => '',
        'type'        => 'text',
        'section'     => 'social',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'min_max_step'=> '',
        'class'       => '',
        'condition'   => '',
        'operator'    => 'and'
      ),
      array(
        'id'          => 'uni_fs_link',
        'label'       => esc_html__( 'Add a link to Foursquare profile', 'bauhaus' ),
        'desc'        => '',
        'std'         => '',
        'type'        => 'text',
        'section'     => 'social',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'min_max_step'=> '',
        'class'       => '',
        'condition'   => '',
        'operator'    => 'and'
      ),
      array(
        'id'          => 'uni_fl_link',
        'label'       => esc_html__( 'Add a link to Flickr profile', 'bauhaus' ),
        'desc'        => '',
        'std'         => '',
        'type'        => 'text',
        'section'     => 'social',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'min_max_step'=> '',
        'class'       => '',
        'condition'   => '',
        'operator'    => 'and'
      ),
      array(
        'id'          => 'uni_dr_link',
        'label'       => esc_html__( 'Add a link to Dribble profile', 'bauhaus' ),
        'desc'        => '',
        'std'         => '',
        'type'        => 'text',
        'section'     => 'social',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'min_max_step'=> '',
        'class'       => '',
        'condition'   => '',
        'operator'    => 'and'
      ),
      array(
        'id'          => 'uni_be_link',
        'label'       => esc_html__( 'Add a link to Behance profile', 'bauhaus' ),
        'desc'        => '',
        'std'         => '',
        'type'        => 'text',
        'section'     => 'social',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'min_max_step'=> '',
        'class'       => '',
        'condition'   => '',
        'operator'    => 'and'
      ),
      array(
        'id'          => 'uni_vk_link',
        'label'       => esc_html__( 'Add a link to Vkontakte profile', 'bauhaus' ),
        'desc'        => '',
        'std'         => '',
        'type'        => 'text',
        'section'     => 'social',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'min_max_step'=> '',
        'class'       => '',
        'condition'   => '',
        'operator'    => 'and'
      ),
    )
  );

  /* settings are not the same update the DB */
  if ( $saved_settings !== $unitheme_settings ) {
    update_option( 'option_tree_settings', $unitheme_settings );
  }

}
?>